// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMKEe7_5LbH3fCuebRgyfwjPkdgzLWk7E',
    appId: '1:778582916768:web:7e87d5ca9365a20b0313c5',
    messagingSenderId: '778582916768',
    projectId: 'restau-5dba7',
    authDomain: 'restau-5dba7.firebaseapp.com',
    storageBucket: 'restau-5dba7.appspot.com',
    measurementId: 'G-E8PNG4SH2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpt0_zY7rZQicZx91DuJUgatjgHUF16-4',
    appId: '1:778582916768:android:5323764c1aeedb440313c5',
    messagingSenderId: '778582916768',
    projectId: 'restau-5dba7',
    storageBucket: 'restau-5dba7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVjITSOzWz1hoMRVrKtwG-eOjA5qlFsbI',
    appId: '1:778582916768:ios:d4ac27d2e26474e10313c5',
    messagingSenderId: '778582916768',
    projectId: 'restau-5dba7',
    storageBucket: 'restau-5dba7.appspot.com',
    iosBundleId: 'com.example.restau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVjITSOzWz1hoMRVrKtwG-eOjA5qlFsbI',
    appId: '1:778582916768:ios:d4ac27d2e26474e10313c5',
    messagingSenderId: '778582916768',
    projectId: 'restau-5dba7',
    storageBucket: 'restau-5dba7.appspot.com',
    iosBundleId: 'com.example.restau',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMKEe7_5LbH3fCuebRgyfwjPkdgzLWk7E',
    appId: '1:778582916768:web:f968c1ea504cf25a0313c5',
    messagingSenderId: '778582916768',
    projectId: 'restau-5dba7',
    authDomain: 'restau-5dba7.firebaseapp.com',
    storageBucket: 'restau-5dba7.appspot.com',
    measurementId: 'G-S5Z43THZ6S',
  );

}